name: Node.js CI
on:
  push:
    branches: master
  pull_request:
    branches: master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
      - run: npm ci
      - run: npm test
      - name: Check fixtures are up to date
        run: |
          node build/update-fixtures
          git diff --quiet
